version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
      day: "saturday"
groups:
  batch:
    patterns:
      - "*"
