name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "20.5.1"
          cache: "npm"
      - run: corepack enable
      - run: npm ci
      - run: npm link grunt-nw-builder
      - run: npm run e2e
